version: "3"

services:
  peluang-client-app:
    container_name: peluang-client-app
    image: peluang-client
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:80"